"""
Package providing generating support files that contain generic code for Dezyne C++ development.

Copyright (c) 2023-2024 Michael van de Ven <michael@ftr-ict.com>
This is free software, released under the MIT License. Refer to dznpy/LICENSE.
"""

# system modules
from typing import Optional, Tuple

# dznpy modules
from ..cpp_gen import Comment, fqn_t
from ..dznpy_version import VERSION
from ..misc_utils import assert_t_optional
from ..scoping import NamespaceIds, ns_ids_t


def initialize_ns(namespace_prefix: Optional[NamespaceIds]) -> Tuple[NamespaceIds, str, str]:
    """Initialize a namespace id that ends with Dzn and optionally prefixed
    with a user specified NamespaceIds. Return the result as a combo of this new
    NamespaceIds, its respective string of the C++ variant and a string suitable
    to preclude in a filename."""
    assert_t_optional(namespace_prefix, NamespaceIds)
    fixed_ns = ns_ids_t('Dzn')

    if namespace_prefix is None:
        return fixed_ns, str(fqn_t(fixed_ns)), "_".join(fixed_ns.items)

    prefixed_ns = namespace_prefix + fixed_ns
    return prefixed_ns, str(fqn_t(prefixed_ns)), "_".join(prefixed_ns.items)


def create_footer() -> str:
    """Create the generic footer for support files."""
    return str(Comment(f'Generated by: dznpy/support_files v{VERSION}'))
