name: 'CI: Build and Test'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install build tools
        run: python -m pip install --upgrade pip build

      - name: Build wheel and sdist
        run: python -m build --wheel --sdist

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: dznpy-wheel
          path: dist/*.whl

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: dznpy-wheel
          path: dist/

      - name: Unpack test data
        run: python test/unpack_test_data.py

      - name: Run test suite
        run: pytest test/
