name: Build and publish dznpy

on:
  push:
    tags:
      - 'v*'   # Only run on version tags like v1.2.3

jobs:
  upload-to-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use PyPI README
        run: cp README_PyPi.md README.md

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install build and twine
        run: |
          python -m pip install --upgrade build twine

      - name: Build the wheel
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
